//! One log file per server run, stored under the app data `logs/` directory.

use crate::script_scanner::Profile;
use serde::{Deserialize, Serialize};
use std::fs::{File, OpenOptions};
use std::io::{BufRead, BufReader, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};
use std::thread;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LogEntry {
    pub filename: String,
    pub path: String,
    pub modified_at: String,
    pub size_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LogUpdate {
    pub text: String,
    pub next_offset: u64,
    pub truncated: bool,
}

/// Create a fresh log file for a run and write the header. Returns its path.
pub fn create_run_log(logs_dir: &Path, profile: &Profile, pid: Option<u32>) -> PathBuf {
    let _ = std::fs::create_dir_all(logs_dir);
    let ts = chrono::Local::now().format("%Y-%m-%d-%H%M%S");
    let path = logs_dir.join(format!("{}-{}.log", profile.id, ts));

    if let Ok(mut f) = File::create(&path) {
        let _ = writeln!(f, "==== Llama Switcher run log ====");
        let _ = writeln!(f, "alias:            {}", profile.alias);
        let _ = writeln!(f, "profileId:        {}", profile.id);
        let _ = writeln!(f, "model:            {}", profile.pretty_model);
        let _ = writeln!(f, "feature:          {}", profile.pretty_feature);
        let _ = writeln!(f, "scriptPath:       {}", profile.script_path);
        let _ = writeln!(f, "workingDirectory: {}", profile.working_directory);
        let _ = writeln!(
            f,
            "startTime:        {}",
            chrono::Local::now().format("%Y-%m-%dT%H:%M:%S")
        );
        if let Some(pid) = pid {
            let _ = writeln!(f, "pid:              {}", pid);
        }
        let _ = writeln!(f, "================================");
        let _ = writeln!(f, "---- process output ----");
    }
    path
}

/// Append a labelled line to a run log (used for stop/exit/health/errors).
pub fn append_line(path: &Path, line: &str) {
    if let Ok(mut f) = OpenOptions::new().create(true).append(true).open(path) {
        let _ = writeln!(
            f,
            "[{}] {}",
            chrono::Local::now().format("%H:%M:%S"),
            line
        );
    }
}

/// Open the log file for appending app-authored status lines.
pub fn open_for_append(path: &Path) -> std::io::Result<File> {
    OpenOptions::new().create(true).append(true).open(path)
}

/// Copy child stdout/stderr into the run log while dropping high-volume status
/// probes generated by Llama Switcher's lightweight `/slots` usage monitor.
pub fn spawn_filtered_pipe<R>(path: PathBuf, reader: R)
where
    R: Read + Send + 'static,
{
    thread::spawn(move || {
        let reader = BufReader::new(reader);
        let Ok(mut file) = open_for_append(&path) else {
            return;
        };

        for line in reader.lines().map_while(Result::ok) {
            if !is_filtered_log_line(&line) {
                let _ = writeln!(file, "{}", line);
            }
        }
    });
}

pub fn list_logs(logs_dir: &Path) -> Vec<LogEntry> {
    let mut entries: Vec<LogEntry> = vec![];
    if let Ok(rd) = std::fs::read_dir(logs_dir) {
        for e in rd.flatten() {
            let path = e.path();
            if path.extension().and_then(|x| x.to_str()) != Some("log") {
                continue;
            }
            let meta = match e.metadata() {
                Ok(m) => m,
                Err(_) => continue,
            };
            let modified_at = meta
                .modified()
                .ok()
                .map(|t| {
                    let dt: chrono::DateTime<chrono::Local> = t.into();
                    dt.format("%Y-%m-%d %H:%M:%S").to_string()
                })
                .unwrap_or_default();
            entries.push(LogEntry {
                filename: e.file_name().to_string_lossy().to_string(),
                path: path.to_string_lossy().to_string(),
                modified_at,
                size_bytes: meta.len(),
            });
        }
    }
    // Newest first.
    entries.sort_by(|a, b| b.modified_at.cmp(&a.modified_at));
    entries
}

pub fn read_log(path: &Path) -> Result<String, String> {
    std::fs::read_to_string(path)
        .map(|text| filter_log_noise(&text))
        .map_err(|e| e.to_string())
}

pub fn read_log_update(path: &Path, offset: u64) -> Result<LogUpdate, String> {
    let mut file = File::open(path).map_err(|e| e.to_string())?;
    let len = file.metadata().map_err(|e| e.to_string())?.len();

    let (start, truncated) = if offset > len { (0, true) } else { (offset, false) };
    file.seek(SeekFrom::Start(start)).map_err(|e| e.to_string())?;

    let mut bytes = Vec::new();
    file.read_to_end(&mut bytes).map_err(|e| e.to_string())?;

    Ok(LogUpdate {
        text: filter_log_noise(&String::from_utf8_lossy(&bytes)),
        next_offset: len,
        truncated,
    })
}

fn filter_log_noise(text: &str) -> String {
    let ends_with_newline = text.ends_with('\n') || text.ends_with('\r');
    let mut filtered = text
        .lines()
        .filter(|line| !is_filtered_log_line(line))
        .collect::<Vec<_>>()
        .join("\n");

    if ends_with_newline && !filtered.is_empty() {
        filtered.push('\n');
    }

    filtered
}

fn is_filtered_log_line(line: &str) -> bool {
    let line = line.trim_end_matches('\r');
    line.contains("srv  update_slots: all slots are idle")
        || line.contains("srv  log_server_r: done request: GET /slots 127.0.0.1 200")
}

pub fn latest_log_path(logs_dir: &Path) -> Option<PathBuf> {
    list_logs(logs_dir).first().map(|e| PathBuf::from(&e.path))
}

/// Delete every log except the most recent one. Returns the count removed.
pub fn clear_old(logs_dir: &Path) -> usize {
    let logs = list_logs(logs_dir);
    let mut removed = 0;
    for entry in logs.into_iter().skip(1) {
        if std::fs::remove_file(&entry.path).is_ok() {
            removed += 1;
        }
    }
    removed
}

#[cfg(test)]
mod tests {
    use super::filter_log_noise;

    #[test]
    fn filters_slots_polling_noise() {
        let text = concat!(
            "real startup line\n",
            "srv  update_slots: all slots are idle\n",
            "srv  log_server_r: done request: GET /slots 127.0.0.1 200\n",
            "real model line\n",
        );

        assert_eq!(filter_log_noise(text), "real startup line\nreal model line\n");
    }
}
